=== HetWaterschapshuis/HyDAMOValidatieModule/hydamo_validation/schemas/rules/rules_1.5.json
{
	"$schema": "http://json-schema.org/schema#",
	"type": "object",
	"required": [
		"schema",
		"hydamo_version",
		"objects"
	],
	"properties": {
		"schema": {
			"type": "string",
			"enum": [
				"1.5"
			]
		},
		"hydamo_version": {
			"type": "string",
			"enum": [
				"2.5"
			]
		},
		"status_object": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": [
					"planvorming",
					"realisatie",
					"gerealiseerd",
					"buiten bedrijf",
					"niet meer aanwezig",
					"te verwijderen",
					"onbekend"
				]
			}
		},
		"objects": {
			"type": "array",
			"items": {
				"$ref": "#/$defs/object_rules_set"
			}
		}
	},
	"$defs": {
		"object_rules_set": {
			"type": "object",
			"required": [
				"object",
				"validation_rules"
			],
			"properties": {
				"object": {
					"$ref": "#/$defs/hydamo_objects"
				},
				"general_rules": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/general_rule"
					}
				},
				"validation_rules": {
					"minItems": 1,
					"type": "array",
					"items": {
						"$ref": "#/$defs/validation_rule"
					}
				}
			}
		},
		"general_rule": {
			"type": "object",
			"required": [
				"id",
				"result_variable",
				"function"
			],
			"properties": {
				"id": {
					"minItems": 1,
					"maxItems": 1,
					"type": "integer"
				},
				"result_variable": {
					"minItems": 1,
					"maxItems": 1,
					"type": "string",
					"pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
				},
				"function": {
					"minItems": 1,
					"maxItems": 1,
					"type": "object",
					"oneOf": [
						{
							"$ref": "#/$defs/buffer"
						},
						{
							"$ref": "#/$defs/difference"
						},
						{
							"$ref": "#/$defs/divide"
						},
						{
							"$ref": "#/$defs/join_parameter"
						},
						{
							"$ref": "#/$defs/multiply"
						},
						{
							"$ref": "#/$defs/object_relation"
						},
						{
							"$ref": "#/$defs/sum"
						}
					]
				}
			}
		},
		"validation_rule": {
			"type": "object",
			"required": [
				"id",
				"name",
				"type",
				"error_type",
				"result_variable",
				"error_message",
				"active",
				"function"
			],
			"properties": {
				"id": {
					"minItems": 1,
					"maxItems": 1,
					"type": "integer"
				},
				"name": {
					"minItems": 1,
					"maxItems": 1,
					"type": "string"
				},
				"type": {
					"minItems": 1,
					"maxItems": 1,
					"type": "string",
					"enum": [
						"logic",
						"topologic"
					]
				},
				"exceptions": {
					"type": "array",
					"items": {
						"type": "string"
					},
					"uniqueItems": true
				},
				"filter": {
					"maxItems": 1,
					"type": "object",
					"oneOf": [
						{
							"$ref": "#/$defs/LE"
						},
						{
							"$ref": "#/$defs/LT"
						},
						{
							"$ref": "#/$defs/GE"
						},
						{
							"$ref": "#/$defs/GT"
						},
						{
							"$ref": "#/$defs/EQ"
						},
						{
							"$ref": "#/$defs/ISIN"
						},
						{
							"$ref": "#/$defs/NOTIN"
						},
						{
							"$ref": "#/$defs/NOTNA"
						}
					]
				},
				"error_type": {
					"minItems": 1,
					"maxItems": 1,
					"type": "string",
					"enum": [
						"critical",
						"non-critical"
					]
				},
				"penalty": {
					"maxItems": 1,
					"type": "integer",
					"minimum": 0,
					"maximum": 9
				},
				"result_variable": {
					"minItems": 1,
					"maxItems": 1,
					"type": "string",
					"pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
				},
				"error_message": {
					"minItems": 1,
					"maxItems": 1,
					"type": "string"
				},
				"active": {
					"minItems": 1,
					"maxItems": 1,
					"type": "boolean"
				},
				"function": {
					"minItems": 1,
					"maxItems": 1,
					"type": "object",
					"oneOf": [
						{
							"$ref": "#/$defs/BE"
						},
						{
							"$ref": "#/$defs/compare_longitudinal"
						},
						{
							"$ref": "#/$defs/consistent_period"
						},
						{
							"$ref": "#/$defs/distant_to_others"
						},
						{
							"$ref": "#/$defs/EQ"
						},
						{
							"$ref": "#/$defs/GE"
						},
						{
							"$ref": "#/$defs/geometry_length"
						},
						{
							"$ref": "#/$defs/GT"
						},
						{
							"$ref": "#/$defs/ISIN"
						},
						{
							"$ref": "#/$defs/LE"
						},
						{
							"$ref": "#/$defs/LT"
						},
						{
							"$ref": "#/$defs/no_dangling_node"
						},
						{
							"$ref": "#/$defs/not_overlapping"
						},
						{
							"$ref": "#/$defs/NOTIN"
						},
						{
							"$ref": "#/$defs/NOTNA"
						},
						{
							"$ref": "#/$defs/join_object_exists"
						},
						{
							"$ref": "#/$defs/snaps_to_hydroobject"
						},
						{
							"$ref": "#/$defs/splitted_at_junction"
						},
						{
							"$ref": "#/$defs/structures_at_boundaries"
						},
						{
							"$ref": "#/$defs/structures_at_intersections"
						},
						{
							"$ref": "#/$defs/structures_at_nodes"
						}
					]
				},
				"tags": {
					"type": "array",
					"items": {
						"type": "string"
					},
					"uniqueItems": true
				}
			}
		},
		"buffer": {
			"type": "object",
			"required": [
				"buffer"
			],
			"properties": {
				"buffer": {
					"type": "object",
					"required": [
						"radius",
						"percentile",
						"coverage"
					],
					"properties": {
						"radius": {
							"type": [
								"string",
								"number"
							]
						},
						"percentile": {
							"type": "integer"
						},
						"coverage": {
							"type": "string",
							"enum": [
								"AHN"
							]
						},
						"fill_value": {
							"type": "number"
						}
					}
				}
			}
		},
		"difference": {
			"type": "object",
			"required": [
				"difference"
			],
			"properties": {
				"difference": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						},
						"absolute": {
							"type": "boolean"
						}
					}
				}
			}
		},
		"divide": {
			"type": "object",
			"required": [
				"divide"
			],
			"properties": {
				"divide": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						}
					}
				}
			}
		},
		"join_parameter": {
			"type": "object",
			"required": [
				"join_parameter"
			],
			"properties": {
				"join_parameter": {
					"type": "object",
					"required": [
						"join_object",
						"join_parameter"
					],
					"properties": {
						"join_object": {
							"$ref": "#/$defs/hydamo_objects"
						},
						"join_parameter": {
							"type": "string"
						},
						"fill_value": {
							"type": "number"
						}
					}
				}
			}
		},
		"multiply": {
			"type": "object",
			"required": [
				"mulitply"
			],
			"properties": {
				"multiply": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						}
					}
				}
			}
		},
		"object_relation": {
			"type": "object",
			"required": [
				"object_relation"
			],
			"properties": {
				"object_relation": {
					"type": "object",
					"required": [
						"related_object",
						"statistic"
					],
					"properties": {
						"related_object": {
							"$ref": "#/$defs/hydamo_objects"
						},
						"related_parameter": {
							"type": "string"
						},
						"statistic": {
							"type": "string",
							"enum": [
								"min",
								"majority",
								"max",
								"sum",
								"count"
							]
						},
						"fill_value": {
							"type": "number"
						}
					}
				}
			}
		},
		"sum": {
			"type": "object",
			"required": [
				"sum"
			],
			"properties": {
				"sum": {
					"type": "object",
					"required": [
						"array"
					],
					"properties": {
						"array": {
							"type": "array",
							"items": {
								"type": [
									"number",
									"string"
								]
							}
						}
					}
				}
			}
		},
		"BE": {
			"type": "object",
			"required": [
				"BE"
			],
			"properties": {
				"BE": {
					"type": "object",
					"required": [
						"parameter",
						"min",
						"max",
						"inclusive"
					],
					"properties": {
						"parameter": {
							"type": "string"
						},
						"min": {
							"type": [
								"number",
								"string"
							]
						},
						"max": {
							"type": [
								"number",
								"string"
							]
						},
						"inclusive": {
							"type": "boolean"
						}
					}
				}
			}
		},
		"consistent_period": {
			"type": "object",
			"required": [
				"consistent_period"
			],
			"properties": {
				"consistent_period": {
					"type": "object",
					"properties": {
						"max_gap": {
							"type": "integer"
						}
					}
				}
			}
		},
		"EQ": {
			"type": "object",
			"required": [
				"EQ"
			],
			"properties": {
				"EQ": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						}
					}
				}
			}
		},
		"GE": {
			"type": "object",
			"required": [
				"GE"
			],
			"properties": {
				"GE": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						}
					}
				}
			}
		},
		"GT": {
			"type": "object",
			"required": [
				"GT"
			],
			"properties": {
				"GT": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						}
					}
				}
			}
		},
		"ISIN": {
			"type": "object",
			"required": [
				"ISIN"
			],
			"properties": {
				"ISIN": {
					"type": "object",
					"required": [
						"parameter",
						"array"
					],
					"properties": {
						"parameter": {
							"type": "string"
						},
						"array": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"LE": {
			"type": "object",
			"required": [
				"LE"
			],
			"properties": {
				"LE": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						}
					}
				}
			}
		},
		"LT": {
			"type": "object",
			"required": [
				"LT"
			],
			"properties": {
				"LT": {
					"type": "object",
					"required": [
						"left",
						"right"
					],
					"properties": {
						"left": {
							"type": [
								"string",
								"number"
							]
						},
						"right": {
							"type": [
								"string",
								"number"
							]
						}
					}
				}
			}
		},
		"NOTIN": {
			"type": "object",
			"required": [
				"NOTIN"
			],
			"properties": {
				"NOTIN": {
					"type": "object",
					"required": [
						"parameter",
						"array"
					],
					"properties": {
						"parameter": {
							"type": "string"
						},
						"array": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"NOTNA": {
			"type": "object",
			"required": [
				"NOTNA"
			],
			"properties": {
				"NOTNA": {
					"type": "object",
					"required": [
						"parameter"
					],
					"properties": {
						"parameter": {
							"type": "string"
						}
					}
				}
			}
		},
		"join_object_exists": {
			"type": "object",
			"required": [
				"join_object_exists"
			],
			"properties": {
				"join_object_exists": {
					"type": "object",
					"required": [
						"join_object"
					],
					"properties": {
						"join_object": {
							"$ref": "#/$defs/hydamo_objects"
						}
					}
				}
			}
		},
		"compare_longitudinal": {
			"type": "object",
			"required": [
				"compare_longitudinal"
			],
			"properties": {
				"compare_longitudinal": {
					"type": "object",
					"required": [
						"parameter",
						"compare_object",
						"compare_parameter",
						"logical_operator",
						"direction"
					],
					"properties": {
						"parameter": {
							"type": "string"
						},
						"compare_object": {
							"$ref": "#/$defs/hydamo_objects"
						},
						"compare_parameter": {
							"type": "string"
						},
						"logical_operator": {
							"type": "string",
							"enum": [
								"GT",
								"LT"
							]
						},
						"direction": {
							"type": "string",
							"enum": [
								"upstream",
								"downstream"
							]
						}
					}
				}
			}
		},
		"distant_to_others": {
			"type": "object",
			"required": [
				"distant_to_others"
			],
			"properties": {
				"distant_to_others": {
					"type": "object",
					"required": [
						"distance"
					],
					"properties": {
						"distance": {
							"type": "number"
						}
					}
				}
			}
		},
		"geometry_length": {
			"type": "object",
			"required": [
				"geometry_length"
			],
			"properties": {
				"geometry_length": {
					"type": "object",
					"required": [
						"length",
						"statistic"
					],
					"properties": {
						"length": {
							"type": "number"
						},
						"statistic": {
							"type": "string",
							"enum": [
								"min",
								"max"
							]
						}
					}
				}
			}
		},
		"no_dangling_node": {
			"type": "object",
			"required": [
				"no_dangling_node"
			],
			"properties": {
				"no_dangling_node": {
					"type": "object",
					"required": [
						"tolerance"
					],
					"properties": {
						"tolerance": {
							"type": "number"
						}
					}
				}
			}
		},
		"not_overlapping": {
			"type": "object",
			"required": [
				"not_overlapping"
			],
			"properties": {
				"not_overlapping": {
					"type": "object",
					"required": [
						"tolerance"
					],
					"properties": {
						"tolerance": {
							"type": "number"
						}
					}
				}
			}
		},
		"snaps_to_hydroobject": {
			"type": "object",
			"required": [
				"snaps_to_hydroobject"
			],
			"properties": {
				"snaps_to_hydroobject": {
					"type": "object",
					"required": [
						"method"
					],
					"properties": {
						"tolerance": {
							"type": "number"
						},
						"method": {
							"type": "string",
							"enum": [
								"overall",
								"intersecting",
								"centroid",
								"ends"
							]
						}
					}
				}
			}
		},
		"splitted_at_junction": {
			"type": "object",
			"required": [
				"splitted_at_junction"
			],
			"properties": {
				"splitted_at_junction": {
					"type": "object",
					"required": [
						"tolerance"
					],
					"properties": {
						"tolerance": {
							"type": "number"
						}
					}
				}
			}
		},
		"structures_at_boundaries": {
			"type": "object",
			"required": [
				"structures_at_boundaries"
			],
			"properties": {
				"structures_at_boundaries": {
					"type": "object",
					"required": [
						"tolerance",
						"structures",
						"areas"
					],
					"properties": {
						"tolerance": {
							"type": "number"
						},
						"structures": {
							"type": "array",
							"items": {
								"type": "string",
								"enum": [
									"gemaal",
									"stuw",
									"duikersifonhevel"
								]
							}
						},
						"areas": {
							"type": "string",
							"enum": [
								"afvoergebiedaanvoergebied",
								"peilafwijkinggebied",
								"peilbesluitgebied",
								"peilgebiedpraktijk",
								"peilgebiedvigerend"
							]
						}
					}
				}
			}
		},
		"structures_at_intersections": {
			"type": "object",
			"required": [
				"structures_at_intersections"
			],
			"properties": {
				"structures_at_intersections": {
					"type": "object",
					"required": [
						"tolerance",
						"structures"
					],
					"properties": {
						"tolerance": {
							"type": "number"
						},
						"structures": {
							"type": "array",
							"items": {
								"type": "string",
								"enum": [
									"duikersifonhevel",
									"aquaduct"
								]
							}
						}
					}
				}
			}
		},
		"structures_at_nodes": {
			"type": "object",
			"required": [
				"structures_at_nodes"
			],
			"properties": {
				"structures_at_nodes": {
					"type": "object",
					"required": [
						"tolerance",
						"structures"
					],
					"properties": {
						"tolerance": {
							"type": "number"
						},
						"structures": {
							"type": "array",
							"items": {
								"type": "string",
								"enum": [
									"gemaal",
									"stuw",
									"bodemval"
								]
							}
						}
					}
				}
			}
		},
		"hydamo_objects": {
			"type": "string",
			"enum": [
				"admingrenswaterschap",
				"afsluitmiddel",
				"afvoeraanvoergebied",
				"afvoergebiedaanvoergebied",
				"aquaduct",
				"beheergrenswaterschap",
				"bijzonderhydraulischobject",
				"bodemval",
				"brug",
				"doorstroomopening",
				"duikersifonhevel",
				"gemaal",
				"grondwaterinfolijn",
				"grondwaterinfopunt",
				"grondwaterkoppellijn",
				"grondwaterkoppelpunt",
				"hydrologischerandvoorwaarde",
				"hydroobject",
				"hydroobject_normgp",
				"imwa_geoobject",
				"kunstwerkopening",
				"lateraleknoop",
				"leggerwatersysteem",
				"leggerwaterveiligheid",
				"meetlocatie",
				"meetwaardeactiewaarde",
				"normgeparamprofiel",
				"normgeparamprofielwaarde",
				"peilafwijkinggebied",
				"peilbesluitgebied",
				"peilgebiedpraktijk",
				"peilgebiedvigerend",
				"pomp",
				"profielgroep",
				"profiellijn",
				"profielpunt",
				"regelmiddel",
				"reglementgrenswaterschap",
				"streefpeil",
				"sturing",
				"stuw",
				"vispassage",
				"vispassagevlak",
				"vuilvang",
				"waterbeheergebied",
				"zandvang"
			]
		}
	}
}

=== HetWaterschapshuis/HyDAMOValidatieModule/tests/data/tasks/test_synthetischedataset_hydamo_2_5/ValidationRules.json
{
	"schema": "1.5",
	"hydamo_version": "2.5",
	"status_object": [
		"planvorming",
		"gerealiseerd"
	],
	"objects": [
		{
			"object": "profiellijn",
			"general_rules": [
				{
					"id": 0,
					"result_variable": "bodemhoogte",
					"function": {
						"object_relation": {
							"statistic": "min",
							"related_object": "profielpunt",
							"related_parameter": "geometry.z"
						}
					}
				},
				{
					"id": 1,
					"result_variable": "bodemhoogte_marge_min",
					"function": {
						"difference": {
							"left": "bodemhoogte",
							"right": 0.2
						}
					}
				}
			],
			"validation_rules": [
				{
					"id": 0,
					"name": "Profiel moet intersecten met een waterlijn",
					"type": "topologic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "op_watergang",
					"error_message": "niet op watergang",
					"active": true,
					"function": {
						"snaps_to_hydroobject": {
							"method": "overall"
						}
					}
				}
			]
		},
		{
			"object": "duikersifonhevel",
			"general_rules": [
				{
					"id": 0,
					"result_variable": "maaiveldhoogte",
					"function": {
						"buffer": {
							"radius": 10,
							"percentile": 95,
							"coverage": "AHN",
							"fill_value": 325
						}
					}
				},
				{
					"id": 1,
					"result_variable": "delta_h",
					"function": {
						"difference": {
							"left": "hoogtebinnenonderkantbov",
							"right": "hoogtebinnenonderkantbene"
						}
					}
				},
				{
					"id": 2,
					"result_variable": "verval",
					"function": {
						"difference": {
							"left": "hoogtebinnenonderkantbov",
							"right": "hoogtebinnenonderkantbene",
							"absolute": true
						}
					}
				},
				{
					"id": 3,
					"result_variable": "slope",
					"function": {
						"divide": {
							"left": "delta_h",
							"right": "lengte"
						}
					}
				}
			],
			"validation_rules": [
				{
					"id": 0,
					"name": "BOK bovenstrooms plausibel (-8m - maaiveld)",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "bok_boven_plausibel",
					"error_message": "bok_boven niet plausibel",
					"exceptions": [
					],
					"active": true,
					"function": {
						"BE": {
							"parameter": "hoogtebinnenonderkantbov",
							"min": -8,
							"max": 325,
							"inclusive": false
						}
					}
				},
				{
					"id": 1,
					"name": "BOK benedenstrooms plausibel (-8m - maaiveld)",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "bok_beneden_plausibel",
					"error_message": "bok_beneden niet plausibel",
					"active": true,
					"function": {
						"BE": {
							"parameter": "hoogtebinnenonderkantbene",
							"min": -8,
							"max": 325,
							"inclusive": false
						}
					}
				},
				{
					"id": 2,
					"name": "BOK bovenstrooms onder maaiveld",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "bok_boven_lt_maaiveld",
					"error_message": "bok_boven > maaiveld",
					"active": true,
					"function": {
						"LT": {
							"left": "hoogtebinnenonderkantbov",
							"right": "maaiveldhoogte"
						}
					}
				},
				{
					"id": 3,
					"name": "BOK benedenstrooms onder maaiveld",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "bok_beneden_lt_maaiveld",
					"error_message": "bok_beneden > maaiveld",
					"active": true,
					"function": {
						"LT": {
							"left": "hoogtebinnenonderkantbene",
							"right": "maaiveldhoogte"
						}
					}
				},
				{
					"id": 4,
					"name": "Lengte groter dan 1 m",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "non-critical",
					"result_variable": "lengte_duiker_groter_dan_1m",
					"error_message": "lengte < 1m",
					"active": true,
					"function": {
						"GT": {
							"left": "lengte",
							"right": 1.0
						}
					}
				},
				{
					"id": 5,
					"name": "Een ronde duikersifonhevel heeft een breedte die gelijk is aan de hoogte",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "non-critical",
					"result_variable": "breedte_eq_hoogte",
					"error_message": "breedteopening != hoogteopening",
					"active": true,
					"filter": {
						"ISIN": {
							"parameter": "vormkoker",
							"array": [
								"Rond"
							]
						}
					},
					"function": {
						"EQ": {
							"left": "breedteopening",
							"right": "hoogteopening"
						}
					}
				},
				{
					"id": 6,
					"name": "Dit object moet precies samenvallen met het hydroobject",
					"type": "topologic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "op_hydroobject",
					"error_message": "hydroobject niet op hydroobject",
					"active": true,
					"function": {
						"snaps_to_hydroobject": {
							"tolerance": 0.01,
							"method": "ends"
						}
					}
				},
				{
					"id": 7,
					"name": "Het bodemverhang van een duiker moet liggen tussen -2 cm/m (omhoog) en 5 cm/m (omlaag)",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "non-critical",
					"result_variable": "verhang_between_2cmpm_en_5cm",
					"error_message": "verhang_onjuist",
					"active": true,
					"function": {
						"BE": {
							"parameter": "slope",
							"min": -0.02,
							"max": 0.05,
							"inclusive": false
						}
					}
				},
				{
					"id": 8,
					"name": "Het bodemverval over een duiker mag niet groter zijn dan 50 cm",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "non-critical",
					"result_variable": "verval_lt_50cm",
					"error_message": "verval_te_groot",
					"active": true,
					"function": {
						"LT": {
							"left": "verval",
							"right": 0.5
						}
					}
				},
				{
					"id": 9,
					"name": "Een duikersifonhevel zal geen overlap met een andere duikersifonhevel hebben",
					"type": "topologic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "geen_overlap",
					"error_message": "overlapping",
					"active": true,
					"function": {
						"not_overlapping": {
							"tolerance": 0.01
						}
					}
				},
				{
					"id": 10,
					"name": "De BOK bovenstrooms mag slechts minimaal lager liggen dan de bovenstroomse bodemhoogte van het hydroobject",
					"type": "topologic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "bok_bov_boven_bodem",
					"error_message": "bok bovenstrooms beneden bodem",
					"active": true,
					"function": {
						"compare_longitudinal": {
							"parameter": "hoogtebinnenonderkantbov",
							"compare_object": "profiellijn",
							"compare_parameter": "bodemhoogte_marge_min",
							"logical_operator": "GT",
							"direction": "upstream"
						}
					}
				},
				{
					"id": 11,
					"name": "De BOK benedenstrooms mag slechts minimaal lager liggen dan de bendenstroomse bodemhoogte van het hydroobject",
					"type": "topologic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "bok_ben_boven_bodem",
					"error_message": "bok bendenstrooms beneden bodem",
					"active": true,
					"function": {
						"compare_longitudinal": {
							"parameter": "hoogtebinnenonderkantbene",
							"compare_object": "profiellijn",
							"compare_parameter": "bodemhoogte_marge_min",
							"logical_operator": "GT",
							"direction": "downstream"
						}
					}
				}
			]
		},
		{
			"object": "kunstwerkopening",
			"validation_rules": [
				{
					"id": 0,
					"name": "hoogstedoorstroomhoogte plausibel (-8m - 325m)",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "hoogstedoorstroomhoogte_plausibel",
					"error_message": "hoogstedoorstroomhoogte niet plausibel",
					"active": true,
					"function": {
						"BE": {
							"parameter": "hoogstedoorstroomhoogte",
							"min": -8,
							"max": 325,
							"inclusive": false
						}
					}
				},
				{
					"id": 1,
					"name": "laagstedoorstroomhoogte plausibel (-8m - 325m)",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "laagstedoorstroomhoogte_plausibel",
					"error_message": "laagstedoorstroomhoogte niet plausibel",
					"active": true,
					"function": {
						"BE": {
							"parameter": "laagstedoorstroomhoogte",
							"min": -8,
							"max": 325,
							"inclusive": false
						}
					}
				},
				{
					"id": 2,
					"name": "De laagste doorstroombreedte moet kleiner zijn dan de hoogste doorstroombreedte, bij een driehoekige of trapeziumvormige opening",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "laagstedrstrmbreedte_lt_hoogstedrstrmbreedte",
					"error_message": "laagstedrstrmbreedte > hoogstedrstrmbreedte",
					"active": true,
					"filter": {
						"ISIN": {
							"parameter": "vormopening",
							"array": [
								"Driehoekig",
								"Trapeziumvormig"
							]
						}
					},
					"function": {
						"LT": {
							"left": "laagstedoorstroombreedte",
							"right": "hoogstedoorstroombreedte"
						}
					}
				},
				{
					"id": 3,
					"name": "De laagste doorstroomhoogte moet kleiner zijn dan de hoogste doorstroomhoogte",
					"type": "logic",
					"validation_rule_set": "basic",
					"error_type": "critical",
					"result_variable": "laagstedrstrmhoogte_lt_hoogstedrstrmhoogte",
					"error_message": "laagstedrstrmhoogte > hoogstedrstrmhoogte",
					"active": true,
					"function": {
						"LT": {
							"left": "laagstedoorstroomhoogte",
							"right": "hoogstedoorstroomhoogte"
						}
					}
				},
				{
					"id": 4,
